cmsblg/urls.py
from django.urls import path
from . import views
from cmsblg.views import *

urlpatterns = [
    path('search/', views.search, name='search'),
    path('facts/', views.facts, name='facts'),
    path('createfact/', CreateFact.as_view(), name='createfaq'),
    path('UpdateFaq/<str:pk>', UpdateFaq.as_view(), name='UpdateFaq'),
    path('deletefaq/<str:pk>', views.deleteFaq, name='deletefaq'),
    path('categorycreateview/', CategoryCreateView.as_view(), name='categorycreateview'),
    path('<slug:category_slug>/<slug:slug>/', views.detail, name='post_detail'),
    path('<slug:slug>/', views.category, name='category_detail')
]

cmsweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from auth_user.views import *
from cmscore.views import *
from cmsblg.views import *
from django.contrib.auth import views as auth_views  

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('admin/', admin.site.urls),
    path('', include('cmscore.urls')), 
    path('', include('auth_user.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='reset_password_form.html'),
         name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_done.html'),
         name="password_reset_complete"),
    path('', include('cmsblg.urls')),   
    # path('', include,('Chat.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cmsblg/models.py
from django.conf import settings
from django.db import models
from multiselectfield import MultiSelectField
from auth_user.models import User
from cmscore.models import AlbumPhoto
import os
import random
from random import choice
# Create your models here.
def get_existing_file_name(instance, filename):
    """
    Returns the filename with a suffix (e.g. "_1") if a file with the same name
    already exists in the media root directory.
    """
    path = os.path.join(settings.MEDIA_ROOT, filename)
    if os.path.exists(path):
        name, ext = os.path.splitext(filename)
        i = 1
        while os.path.exists(os.path.join(settings.MEDIA_ROOT, f"{name}_{i}{ext}")):
            i += 1
        # Check if the file with the original filename exists
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, instance.image.name)):
            return instance.image.name
        return f"{name}_{i}{ext}"
    return filename

class Category(models.Model):
    # blgcat_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    caption = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created_by = models.CharField(max_length=50, blank=True, null=True)
    modified_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    modified_by = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Categories'
        # managed = False
        # db_table = 'cmsblg_category'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/%s/' % self.slug

class Post(models.Model):
    ACTIVE = 'active'
    DRAFT = 'draft'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DRAFT, 'Draft')
    )
    # blgpost_id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, null=True, blank=True, related_name='posts', on_delete=models.CASCADE )
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    intro = models.TextField()
    body = models.TextField()
    featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    image = models.ManyToManyField('PostImages', related_name='postimg', blank=True)
    modified_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    modified_by = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ('-created_at',)
        # managed = False
        # db_table = 'cmsblg_post'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/%s/%s/' % (self.category.slug, self.slug)
    
class PostImages(models.Model):
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE, null=True, blank=True)
    albumphoto = models.ForeignKey(AlbumPhoto, related_name='album_photo_images', default=None, on_delete=models.CASCADE, null=True, blank=True)
    images = models.ImageField(upload_to=get_existing_file_name, verbose_name='Image', blank=True)

    def __str__(self):
        return self.images.name

# class Comment(models.Model):
#     post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
#     name = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)
#     email = models.EmailField()
#     body = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.body
    
    #upgrade comment model
class Comment(models.Model):
    name = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField()
    # created_date = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    modified_by = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f'Comment by {self.user} on {self.post}'

    @property
    def is_parent(self):
        return not self.parent
    
    class Meta:
        ordering = ['-created_at']
        # managed = False
        # db_table = 'cmsblg_comment'

class Fact(models.Model):
    # faq_id = models.AutoField(primary_key=True)
    question = models.TextField()
    answer = models.TextField()
    img = models.ImageField(upload_to='Fact', blank=True, null=True)
    category = models.ForeignKey(Category, models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created_by = models.CharField(max_length=255, null=True)
    modified_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    modified_by = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
    #     managed = False
        db_table = 'cmsblg_faq'

    def __str__(self):
        return self.question

cmsblg/forms.py
from django import forms

from .models import Comment, Category, Fact

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title', 'caption', )

class FactForm(forms.ModelForm):
    class Meta:
        model = Fact
        fields = ['question', 'answer', 'img', 'category']
        labels = '__all__'

cmsblg/views.py
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required, permission_required
from .forms import CommentForm, CategoryForm, FactForm
from .models import Post, Category, Fact
from cmscore.models import Album, AlbumPhoto
from cmi_models.models import Commodity, Project, Program, CMI
from django.utils.text import slugify
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.db import connection

def detail(request, category_slug, slug):
    post = get_object_or_404(Post, slug=slug, status=Post.ACTIVE)
    posts = Post.objects.all()

    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = post
                comment.name = request.user  # set the name field to the current user
                comment.save()
                return redirect('post_detail', category_slug=post.category.slug, slug=post.slug)
        else:
            return redirect('login')
    else:
        form = CommentForm()

    return render(request, 'cmsblg/detail.html', {'post': post, 'posts': posts, 'form': form})

def category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.filter(status=Post.ACTIVE)
    albumnews = AlbumPhoto.objects.filter(news=True)
    albumevents = AlbumPhoto.objects.filter(events=True)

    return render(request, 'cmsblg/category.html', {'category': category, 'posts': posts, 'albumnews': albumnews, 'albumevents': albumevents})

def search(request):
    query = request.GET.get('query', '')

    posts = Post.objects.filter(status=Post.ACTIVE).filter(Q(title__icontains=query) | Q(intro__icontains=query) | Q(body__icontains=query))
    commodities = Commodity.objects.filter(Q(name__icontains=query) | Q(detail__icontains=query))
    photo = AlbumPhoto.objects.filter(Q(name__icontains=query) | Q(caption__icontains=query))
    project = Project.objects.filter(Q(title__icontains=query))
    category = Category.objects.filter(Q(title__icontains=query) | Q(slug__icontains=query))
    cmis = CMI.objects.filter(Q(agency_id__icontains=query) | Q(name__icontains=query) | Q(agency_code__icontains=query))


    return render(request, 'cmsblg/search.html', {'posts': posts, 'project': project, 'commodities': commodities, 'category': category, 'photo': photo, 'cmis': cmis, 'query': query})

def facts(request):
    faqs = Fact.objects.all()

    return render(request, 'faqs.html', {'faqs': faqs})

class CreateFact(LoginRequiredMixin, CreateView):
    model = Fact
    form_class = FactForm
    template_name = 'createcommodity.html'
    success_url = reverse_lazy('dashboard')
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class UpdateFaq(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Fact
    form_class = FactForm
    success_url = reverse_lazy('dashboard')
    template_name = 'commodity_update.html'

    def test_func(self):
        return self.request.user.is_staff or self.request.user.is_superuser

@staff_member_required(login_url='/login')
def deleteFaq(request, pk):
    faq = get_object_or_404(Fact, id=pk)
    try:
        faq.delete()
        messages.success(request, 'Faq deleted successfully')
    except Exception as e:
        messages.error(request, f'Error deleting Faq: {str(e)}')
    return redirect('/dashboard')

class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'createcategory.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        slug = slugify(form.cleaned_data['title'])
        count = 1
        while Category.objects.filter(slug=slug).exists():
            slug = f"{slug}-{count}"
            count += 1
        form.instance.slug = slug
        return super().form_valid(form)

cmsblg/templates/cmsblg/category.html
{% extends 'core/base.html' %}

{% block title %}{{ category.title }} | {% endblock %}

{% block content %}
    <section class="hero">
        <div class="hero-body">
            <div class="container">
                <section class="section">
                            <div class="section-header d-flex justify-content-between align-items-center mb-5">
                            <div><a href="{% url 'community' %}" class="more">Back To Forum</a></div>
                            </div>
                    <div class="columns">
                        <div class="column is-8 is-offset-2 align-items-center">
                            <h1 class="page-title">{{category.title}}</h1>
                            <hr style="color: #008001;">
                            {% for post in albumnews %}
                              <div class="card mb-5" style="max-width: 40rem; margin: auto; text-align-last: center;">
                                <div class="container text-center">
                                  <div class="row">
                                    {% for post_image in post.albumphotoimages_set.all %}
                                      {% if post_image.images %}
                                        <div class="col">
                                          <a href="{% url 'gallery' %}">
                                            <img src="{{ post_image.images.url }}" class="card-img-top mt-3" alt="..." style="max-width:300px; height: 200px; max-height: 200px; object-fit: cover;">
                                          </a>
                                        </div>
                                        {% if forloop.counter == 2 %}
                                          </div>
                                          <div class="row">
                                        {% endif %}
                                      {% endif %}
                                    {% endfor %}
                                  </div>
                                </div>
                                <div class="card-body">
                                  <a href="{% url 'gallery' %}">
                                    <h5 class="card-title">{{ post.name }}</h5>
                                  </a>
                                  <p class="card-text">{{ post.caption }}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                  <li class="list-group-item">{{ post.created_at|timesince }} ago</li>
                                  <li class="list-group-item">AlBUM</li>
                                </ul>
                              </div>
                            {% endfor %}
                            {% for post in albumnews %}
                              <div class="card mb-5" style="max-width: 40rem; margin: auto; text-align-last: center;">
                                <div class="container text-center">
                                  <div class="row">
                                    {% for post_image in post.albumphotoimages_set.all %}
                                      {% if post_image.images %}
                                        <div class="col">
                                          <a href="{% url 'gallery' %}">
                                            <img src="{{ post_image.images.url }}" class="card-img-top mt-3" alt="..." style="max-width:300px; height: 200px; max-height: 200px; object-fit: cover;">
                                          </a>
                                        </div>
                                        {% if forloop.counter == 2 %}
                                          </div>
                                          <div class="row">
                                        {% endif %}
                                      {% endif %}
                                    {% endfor %}
                                  </div>
                                </div>
                                <div class="card-body">
                                  <a href="{% url 'gallery' %}">
                                    <h5 class="card-title">{{ post.name }}</h5>
                                  </a>
                                  <p class="card-text">{{ post.caption }}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                  <li class="list-group-item">{{ post.created_at|timesince }} ago</li>
                                  <li class="list-group-item">AlBUM</li>
                                </ul>
                              </div>
                            {% endfor %}
                            {% for post in posts %}
                              <div class="card mb-5 border-0" style="max-width: 40rem; margin: auto; text-align-last: center;">
                                <div class="container text-center">
                                  <div class="row">
                                                                        {% if post.postimages_set.all %}
                                    {% for post_image in post.postimages_set.all %}
                                      {% if post_image.images %}
                                        <div class="col">
                                          <a href="{% url 'post_detail' post.category.slug post.slug %}">
                                            <img src="{{ post_image.images.url }}" class="card-img-top mt-3" alt="..." style="max-width:300px; height: 200px; max-height: 200px; object-fit: cover;">
                                          </a>
                                        </div>
                                        {% if forloop.counter == 2 %}
                                          </div>
                                          <div class="row">
                                        {% endif %}
                                      {% endif %}
                                    {% endfor %}
                                    {% else %}
                                    {% for post_image in post.image.all %}
                                      {% if post_image.images %}
                                        <div class="col">
                                          <a href="{% url 'post_detail' post.category.slug post.slug %}">
                                            <img src="{{ post_image.images.url }}" class="card-img-top mt-3" alt="..." style="max-width:300px; height: 200px; max-height: 200px; object-fit: cover;">
                                          </a>
                                        </div>
                                        {% if forloop.counter == 2 %}
                                          </div>
                                          <div class="row">
                                        {% endif %}
                                      {% endif %}
                                      {% endfor %}
                                      {% endif %}
                                  </div>
                                </div>
                                <div class="card-body">
                                  <a href="{% url 'post_detail' post.category.slug post.slug %}">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                  </a>
                                  <p class="card-text">{{ post.intro }}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                  <li class="list-group-item" style="background-color: #008001; color: #ffffff;">{{ post.created_at|timesince }} ago</li>
                                  <li class="list-group-item" style="background-color: #66b365; color: #ffffff;">Comments: {{ post.comments.count }}</li>
                                </ul>
                              </div>
                            {% empty %}
                              <div class="content">
                                <p>There is currently no post</p>
                              </div>
                            {% endfor %}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
{% endblock %}

cmsblg/templates/cmsblg/detail.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block title %}{{ post.title }} | {% endblock %}

{% block content %}
<section class="single-post-content">
      <div class="container">
            <div class="section-header d-flex justify-content-between align-items-center mb-5">
            <div><a href="{% url 'allpost' %}" class="more">Back To All Post</a></div>
            </div>
        <div class="row">
          <div class="col-md-9 post-content" data-aos="fade-up">

            <!-- ======= Single Post Content ======= -->
            <div class="col-lg-4">
              <div class="post-entry-1 lg">
                <div class="d-flex align-items-center author">
                  <div class="photo"><img src="assets/img/person-1.jpg" alt="" class="img-fluid"></div>
                  <div class="name">
                    <h3 class="m-0 p-0">{{post.author}}</h3>
                  </div>
                </div>
              </div>
            </div>

            <div class="single-post">
              <div class="post-meta"><span class="date">Posted</span> <span class="mx-1">&bullet;</span> <span>{{post.created_at|date:"Y-m-d"}}</span></div>
              <h1 class="mb-5">{{post.title}}</h1>
              <div id="carouselExampleFade" class="carousel slide">
                <div class="carousel-inner">
                  {% for post_image in post.postimages_set.all %}
                    {% if post_image.images %}
                      <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <a href="{{ post_image.images.url }}"><img src="{{ post_image.images.url }}" style="max-height: 700px; object-fit: scale-down;" class="d-block w-100" alt="..."></a> 
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
              <p>{{post.intro|slice:":1"}}{{post.intro}}</p>
              <p>{{post.body}}</p>
              </div><!-- End Single Post Content -->

              <hr style="color: #008001;" class="hr" />

            <!-- ======= Comments ======= -->
            <div class="comments">
              <h5 class="comment-title py-4">Comments: {{ post.comments.all|length|default:"0" }}</h5>
              {% for comment in post.comments.all %}
              <div class="comment d-flex mb-4">
                <div class="flex-shrink-0">
                  <div class="avatar avatar-sm rounded-circle">
                    <!-- <img class="avatar-img" src="/static/assets/img/.jpg" alt="" class="img-fluid"> -->
                  </div>
                </div>
                <div class="flex-grow-1 ms-2 ms-sm-3">
                  <div class="comment-meta d-flex align-items-baseline">
                    <h6 class="me-2">{{comment.name}}</h6>
                    <span class="text-muted">{{comment.created_at|timesince}}</span>
                  </div>
                  <div class="comment-body">
                    {{comment.body}}
                  </div>
                  <!-- <div class="comment-replies bg-light p-3 mt-3 rounded">
                    <h6 class="comment-replies-title mb-4 text-muted text-uppercase">2 replies</h6>

                    <div class="reply d-flex mb-4">
                      <div class="flex-shrink-0">
                        <div class="avatar avatar-sm rounded-circle">
                          <img class="avatar-img" src="assets/img/person-4.jpg" alt="" class="img-fluid">
                        </div>
                      </div>
                      <div class="flex-grow-1 ms-2 ms-sm-3">
                        <div class="reply-meta d-flex align-items-baseline">
                          <h6 class="mb-0 me-2">to be updated</h6>
                          <span class="text-muted">2d</span>
                        </div>
                        <div class="reply-body">
                          to be updated
                        </div>
                      </div>
                    </div>
                  </div> -->
                </div>
              </div>
              {% endfor %}
            </div><!-- End Comments -->

            <hr class="hr" />

            <!-- ======= Comments Form ======= -->
            <div class="row justify-content-center mt-5">

              <div class="col-lg-12">
                <h5 class="comment-title">Leave a Comment</h5>
                <div class="row">
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:"form-control" }}
                      </div>
                    {% endfor %}
                    <button class="butn btn btn-lg mt-4 w-100">Post comment</button>
                  </form>
                </div>
              </div>
            </div><!-- End Comments Form -->

          </div>
          <div class="col-md-3">
            <!-- ======= Sidebar ======= -->
            <div class="aside-block">

              <ul class="nav nav-pills custom-tab-nav mb-4" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link active" id="pills-popular-tab" data-bs-toggle="pill" data-bs-target="#pills-popular" type="button" role="tab" aria-controls="pills-popular" aria-selected="true">Latest Post</button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">

                <!-- Popular -->
                <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">

                  <div class="post-entry-1 border-bottom">
                    {% for post in posts %}
                    <div class="post-meta"><span class="date">Post</span> <span class="mx-1">&bullet;</span> <span>{{post.created_at|date:"Y-m-d"}}</span></div>
                    <h2 class="mb-2"><a href="#">{{post.title}}</a></h2>
                    <span class="author mb-3 d-block">User : {{ post.author}}</span>
                    {% endfor %}
                  </div>
                </div> <!-- End Popular -->

              </div>
            </div>

            <div class="aside-block">
              <h3 class="aside-title">Options</h3>
              <ul class="aside-links list-unstyled">
                <li><a href="{% url 'allpost' %}"><i class="bi bi-chevron-right"></i> All Posts</a></li>
                <li><a href="{% url 'community' %}"><i class="bi bi-chevron-right"></i> Categories</a></li>
                <li><a href="{% url 'facts' %}"><i class="bi bi-chevron-right"></i> FAQs</a></li>
              </ul>
            </div><!-- End Categories -->

          </div>
        </div>
      </div>
    </section>
    {% endblock %}
<!-- <section class="hero">
    <div class="hero-body">
        <div class="container">
            <section class="section">
                {% if post.image %}
                    <figure class="image mb-6">
                        <img src="{{ post.image.url }}">
                    </figure>
                {% endif %}

                <div class="columns">
                    <div class="column is-8 is-offset-2">
                        <div class="content is-medium">

                            <h2 class="subtitle is-4">{{ post.created_at|timesince }} ago</h2>
                            <h1 class="title">{{ post.title }}</h1>
                            <p><strong>{{ post.intro }}</strong></p>
                            <p>{{ post.body }}</p>

                            <p><small>Category: <a href="{% url 'category_detail' post.category.slug %}">{{ post.category }}</a></small></p>

                            <hr>

                            <h2 class="subtitle is-4">Comments</h2>

                            <form action="" method="post" class="mb-6">
                                {% csrf_token %}

                                {{ form.as_p }}

                                <div class="field">
                                    <div class="control">
                                        <button class="button is-success">Submit comment</button>
                                    </div>
                                </div>
                            </form>

                            {% for comment in post.comments.all %}
                                <article class="media box">
                                    <div class="media-content">
                                        <strong>{{ comment.name }}</strong> <small>{{ comment.created_at|timesince }} ago</small><br>
                                        {{ comment.body }}
                                    </div>
                                </article>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</section> -->